/* All standard header including. */

#pragma once

#include <cfloat>
#include <climits>
#include <compare>
#include <coroutine>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <exception>
#include <initializer_list>
#include <limits>
#include <new>
#include <source_location>
#include <typeinfo>
#include <version>
#include <concepts>
#include <cassert>
#include <cerrno>
#include <stdexcept>
#include <system_error>
#include <memory>
#include <memory_resource>
#include <scoped_allocator>
#include <ratio>
#include <type_traits>
#include <any>
#include <bitset>
#include <bit>
#include <charconv>
#include <expected>
#include <format>
#include <functional>
#include <optional>
#include <tuple>
#include <typeindex>
#include <utility>
#include <variant>
#include <array>
#include <deque>
#include <flat_map>
#include <flat_set>
#include <forward_list>
#include <list>
#include <map>
#include <mdspan>
#include <queue>
#include <set>
#include <span>
#include <stack>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <iterator>
#include <ranges>
#include <algorithm>
#include <numeric>
#include <cctype>
#include <cstring>
#include <cuchar>
#include <cwchar>
#include <cwctype>
#include <string_view>
#include <string>
#include <clocale>
#include <codecvt>
#include <locale>
#include <regex>
#include <cfenv>
#include <cmath>
#include <complex>
#include <numbers>
#include <random>
#include <stdckdint.h>
#include <valarray>
#include <chrono>
#include <ctime>
#include <ccomplex>
#include <ciso646>
#include <cstdalign>
#include <cstdbool>
#include <ctgmath>
#include <cinttypes>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iosfwd>
#include <iostream>
#include <ios>
#include <istream>
#include <ostream>
#include <print>
#include <sstream>
#include <streambuf>
#include <strstream>
#include <syncstream>
#include <atomic>
#include <barrier>
#include <condition_variable>
#include <future>
#include <latch>
#include <mutex>
#include <semaphore>
#include <shared_mutex>
#include <stdatomic.h>
#include <stop_token>
#include <thread>
#include <execution>
