from __future__ import annotations


def timestamp() -> int: ...

def timestamp_ms() -> int: ...

def current_date_time_string() -> str: ...

def current_year() -> int: ...

def current_month() -> int: ...

def current_day() -> int: ...

def current_hour() -> int: ...

def current_minute() -> int: ...

def current_second() -> int: ...

def sleep(seconds: int) -> None: ...

def sleep_ms(milliseconds: int) -> None: ...


class Datetime:
    year: int
    month: int
    day: int
    minute: int
    second: int
    timestamp: int

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __lt__(self, other: "Datetime") -> bool: ...
    def __gt__(self, other: "Datetime") -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
