from __future__ import annotations
from typing import List


class FileException(Exception): ...


class FileNotFoundException(FileException): ...


class FileReadFailException(FileException): ...


class FileWriteFailException(FileException): ...


class FileOpenFailException(FileException): ...


class FileInvalidAttributesException(FileException): ...


def exists(name: str) -> bool: ...

def is_regular_file(name: str) -> bool: ...

def relative_path_of(name: str) -> str: ...

def abs_path_of(name: str) -> str: ...

def extension_of(name: str) -> str: ...

def stem_of(name: str) -> str: ...

def is_read_only(name: str) -> bool: ...

def file_size(name: str) -> int: ...

def is_hidden(name: str) -> bool: ...

def get_working_dir() -> str: ...

def change_dir(path: str) -> None: ...

def copy_file(src: str, dst: str) -> None: ...

def move_file(src: str, dst: str) -> None: ...

def rename_file(src: str, new_name: str) -> None: ...

def is_valid_filename(name: str) -> bool: ...

def make_dir(path: str) -> None: ...

def remove_file(path: str) -> None: ...

def remove_dir(path: str) -> None: ...

def read_file(name: str) -> str: ...

def read_binary(name: str) -> List[int]: ...

def write_file(name: str, s: str) -> None: ...

def append_file(name: str, s: str) -> None: ...

def write_binary(name: str, bin: List[int]) -> None: ...


class TempFile:
    def __init__(self, file: str = "") -> None: ...
    def get_content(self) -> str: ...
    def get_binary(self) -> List[int]: ...
    def get_name(self) -> str: ...
    def remove(self) -> None: ...
