from __future__ import annotations
from typing import List


def len(s: str) -> int: ...

def left(s: str, len: int) -> str: ...

def right(s: str, len: int) -> str: ...

def mid(s: str, start: int, len: int = ...) -> str: ...

def getleft(s: str, len: int) -> str: ...

def getright(s: str, len: int) -> str: ...

def getmid(s: str, start: int, len: int = ...) -> str: ...

def upper(s: str) -> str: ...

def lower(s: str) -> str: ...

def title(s: str) -> str: ...

def capitalize(s: str) -> str: ...

def caseswap(s: str) -> str: ...

def strip(s: str) -> str: ...

def split(s: str, sep: str) -> List[str]: ...

def count(s: str, subs: str) -> int: ...

def find(s: str, subs: str) -> int: ...

def repeat(s: str, time: int = ...) -> str: ...

def reverse(s: str) -> str: ...
