from typing import Callable

class Stopwatch:
    def __init__(self) -> None: ...
    def start(self) -> int: ...
    def stop(self) -> int: ...
    def reset(self) -> int: ...
    def get_time(self) -> int: ...
    def terminate(self) -> int: ...
    def is_running(self) -> bool: ...

class Timer:
    def __init__(self, interval_ms: int, func: Callable[[], None]) -> None: ...
    def stop(self) -> None: ...
    def continue_(self) -> None: ...